2025-11-01 02:07:43,563 - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.43.105:5000
2025-11-01 02:07:43,563 - INFO - [33mPress CTRL+C to quit[0m
2025-11-01 02:11:29,987 - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.43.105:5000
2025-11-01 02:11:29,987 - INFO - [33mPress CTRL+C to quit[0m
2025-11-01 02:18:54,618 - ERROR - Error en handle_photo: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2025-11-01 02:49:03,140 - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.43.105:5000
2025-11-01 02:49:03,188 - INFO - [33mPress CTRL+C to quit[0m
2025-11-01 02:50:50,031 - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.43.105:5000
2025-11-01 02:50:50,034 - INFO - [33mPress CTRL+C to quit[0m
2025-11-01 02:52:40,466 - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: can't parse entities: Can't find end of the entity starting at byte offset 882
2025-11-01 02:52:40,487 - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\Reima\AppData\Local\Programs\Python\Python312\Lib\site-packages\telebot\__init__.py", line 1235, in __threaded_polling
    self.worker_pool.raise_exceptions()
  File "C:\Users\Reima\AppData\Local\Programs\Python\Python312\Lib\site-packages\telebot\util.py", line 150, in raise_exceptions
    raise self.exception_info
  File "C:\Users\Reima\AppData\Local\Programs\Python\Python312\Lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "C:\Users\Reima\AppData\Local\Programs\Python\Python312\Lib\site-packages\telebot\__init__.py", line 8945, in _run_middlewares_and_handler
    result = handler['function'](message)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Programacion\Proyectos personales\Github Repositorios\Personales\Text-Recognition-Telegram-bot-OCR-\main.py", line 123, in cmd_message
    traductor.ia.send_message(m.text.strip(), bot, m.chat.id)
  File "d:\Programacion\Proyectos personales\Github Repositorios\Personales\Text-Recognition-Telegram-bot-OCR-\main_classes.py", line 99, in send_message
    clase_enviar.send_message(destinatario, res.json()["choices"][0]["message"]["content"].replace("**", "*").replace("!", "!")[:4000], parse_mode='Markdown')
  File "C:\Users\Reima\AppData\Local\Programs\Python\Python312\Lib\site-packages\telebot\__init__.py", line 1775, in send_message
    apihelper.send_message(
  File "C:\Users\Reima\AppData\Local\Programs\Python\Python312\Lib\site-packages\telebot\apihelper.py", line 273, in send_message
    return _make_request(token, method_url, params=payload, method='post')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Reima\AppData\Local\Programs\Python\Python312\Lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Reima\AppData\Local\Programs\Python\Python312\Lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: can't parse entities: Can't find end of the entity starting at byte offset 882

2025-11-01 02:53:07,944 - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.43.105:5000
2025-11-01 02:53:07,947 - INFO - [33mPress CTRL+C to quit[0m
2025-11-01 02:53:44,104 - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.43.105:5000
2025-11-01 02:53:44,107 - INFO - [33mPress CTRL+C to quit[0m
